services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    environment:
      # - DJANGO_SETTINGS_MODULE=laba6.settings
      - DEBUG=1